/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 9.0.1   2018-08-27

The MIT License (MIT)
Copyright (c) 2018 STMicroelectronics

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/

/*
 * TO DO:
 * - hide all functions in the sup_ll_driver
 * - crc8 / crc16
 */

/* Includes */

#include "stm32f10x.h"
#include "ringbuffer.h"
#include "utils.h"
#include "usart.h"
#include "sup_ll_driver.h"
#include "sup.h"
#include "test_module.h"


int main(void)
{
	RingBuff_t* RingBuffer_ptr;
	uint8_t au8rawData[SUP_BUFFER_SIZE];
	uint8_t au8data[SUP_MAX_LENGTH];
	uint16_t u16rawDataLength,u16dataLength,u16temp;
	int8_t s8retVal;
	uint8_t u8temp;



	SystemInit();

	RCC->APB2ENR |= RCC_APB2ENR_IOPCEN;

	GPIOC->CRH = GPIO_CRH_MODE13_0;
	GPIOC->ODR |= GPIO_ODR_ODR13;

	usartInit(115200);

	wait_1ms(10);
	usartClearFlagsAndBuffer();
	wait_1ms(100);
	RingBuffer_ptr = usartGetRingBuffPointer();

	init_module();
	s8retVal = sup_get_properties(&u8temp,0,0);
	s8retVal = sup_get_properties(&u8temp,0,1);
	s8retVal = sup_get_properties(&u8temp,0,2);
	s8retVal = sup_get_properties(&u8temp,1,0);



	/*
	au8data[0] = 0x12;
	au8data[1] = 0x34;
	au8data[2] = 0x57;
	sup_send_busy();
	sup_send(0x02,au8data,0x03);
	sup_send_busy();
	*/

	/*
	au8data[0] = 0xFF;
	sup_send_busy();
	sup_send(0x0,au8data,0x01);
	sup_send_busy();
	*/

//	au8data[0] = 0x3f;
//	au8data[1] = 0x89;
//
//	u16temp = crc16(au8data,2);


//	au8rawData[0] = 0x3f;
//	au8rawData[1] = 0x89;
//	s8retVal = sup_get_packet(au8data,&u16dataLength,au8rawData,2);
//	s8retVal = sup_unpackage(au8rawData,&u16rawDataLength,au8data,u16dataLength);


	__enable_irq();


	while(1)
	{
		if(RingBuffer_CountData(RingBuffer_ptr,0x7E))
		{
			u16rawDataLength = RingBuffer_RemoveUntilDelimiter(RingBuffer_ptr,au8rawData,SUP_BUFFER_SIZE,0x7E);
			s8retVal = sup_receive(au8data,&u16dataLength,au8rawData,u16rawDataLength);
			if(s8retVal == 0)
			{
				switch(au8data[0])
				{
				case WRITE_SYS:

				break;

				case WRITE_SYS_REPLY:

				break;

				case READ_SYS:

				break;

				case READ_SYS_REPLY:

				break;

				case WRITE_DATA:

				break;

				case WRITE_DATA_REPLY:

				break;

				case READ_DATA:

				break;

				case READ_DATA_REPLY:

				break;

				case SETUP_JOB:

				break;

				case SETUP_JOB_REPLY:

				break;

				case CHANGE_JOB:

				break;

				case CHANGE_JOB_REPLY:

				break;

				case DELETE_JOB:

				break;

				case DELETE_JOB_REPLY:

				break;

				case GET_JOB:

				break;

				case GET_JOB_REPLY:

				break;

				case START_JOB:

				break;

				case START_JOB_REPLY:

				break;

				case STOP_JOB:

				break;

				case STOP_JOB_REPLY:

				break;

				case JOB_DATA:

				break;
				}
				while(sup_send_busy());
				sup_send(au8data,u16dataLength);
			}
		}
//		GPIOC->ODR ^= GPIO_ODR_ODR13;
//		wait_1ms(100);
	}
}

